'use client'
import {FormEvent, useMemo, useState} from 'react'

type Item={title:string;place:string;type:string;image:string;price:string;desc:string}
const trips:Item[]=[
 {title:'Méditerranée & escapade',place:'Tunisie',type:'Séjour',image:'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Une escapade pensée selon vos dates et votre budget.'},
 {title:'Istanbul découverte',place:'Turquie',type:'City break',image:'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Culture, quartiers emblématiques et moments libres.'},
 {title:'Dubai expérience',place:'Émirats arabes unis',type:'Premium',image:'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Construisez un séjour flexible avec hôtel et vols.'},
 {title:'Paris en liberté',place:'France',type:'City break',image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Un itinéraire personnalisé pour découvrir Paris.'},
 {title:'Antalya soleil',place:'Turquie',type:'Famille',image:'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Séjour détente, hébergement et transport à organiser.'},
 {title:'Omra sur demande',place:'Arabie Saoudite',type:'Omra',image:'https://images.unsplash.com/photo-1564769625392-651b89c2e7b7?auto=format&fit=crop&w=900&q=80',price:'Sur devis',desc:'Présentez votre projet et recevez les informations disponibles.'}
]
const destinations=[['Turquie','Istanbul, Antalya','https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=900&q=80'],['Tunisie','Hammamet, Djerba','https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80'],['Émirats','Dubai, Abu Dhabi','https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=80'],['France','Paris, Côte d’Azur','https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80']]
const services=[['✈️','Billetterie','Recherche et demande de vols selon vos dates.'],['🏨','Hôtellerie','Trouvez une solution d’hébergement adaptée à votre projet.'],['🛂','Visa','Accompagnement documentaire selon la destination.'],['🕋','Omra','Demande personnalisée pour votre projet de Omra.']]

function Header(){return <><div className="top"><div className="container"><span>In Vacation Travel · Khemis Miliana</span><span>0552 42 65 12 · Lun–Ven 09:00–17:00</span></div></div><header className="nav"><div className="container navin"><a className="logo" href="/"><span className="mark">✈</span>In Vacation<span style={{color:'var(--cyan)'}}>.</span></a><nav className="links"><a href="/voyages">Voyages</a><a href="/destinations">Destinations</a><a href="/billetterie">Billetterie</a><a href="/hotellerie">Hôtellerie</a><a href="/visa">Visa</a><a href="/omra">Omra</a><a href="/contact">Contact</a></nav><a className="btn primary" href="/demande">Demander un devis</a></div></header></>}
function Footer(){return <footer className="footer"><div className="container footergrid"><div><h3>In Vacation Travel</h3><p style={{lineHeight:1.7}}>Une plateforme moderne pour préparer votre prochain voyage avec un accompagnement humain.</p><p>44 Rue Colonel Bougara, Khemis Miliana 44000</p></div><div><h3>Explorer</h3><a href="/voyages">Voyages</a><a href="/destinations">Destinations</a><a href="/offres">Offres</a></div><div><h3>Services</h3><a href="/billetterie">Billetterie</a><a href="/hotellerie">Hôtellerie</a><a href="/visa">Visa</a><a href="/omra">Omra</a></div><div><h3>Contact</h3><a href="tel:+213552426512">0552 42 65 12</a><a href="/contact">Nous contacter</a><a href="/demande">Demander un devis</a></div></div><div className="container" style={{borderTop:'1px solid #193340',marginTop:35,paddingTop:20,fontSize:12}}>© {new Date().getFullYear()} In Vacation Travel. Les disponibilités et tarifs sont à confirmer par l’agence.</div></footer>}
function Search(){const [q,setQ]=useState('');return <div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Où voulez-vous partir ? Ex. Istanbul en famille"/><select><option>Type de voyage</option><option>Séjour</option><option>City break</option><option>Omra</option></select><select><option>Voyageurs</option><option>1–2</option><option>3–5</option><option>6+</option></select><a className="btn primary" href={'/voyages'+(q?`?q=${encodeURIComponent(q)}`:'')}>Rechercher</a></div>}
function Card({x}:{x:Item}){return <article className="card"><div className="photo" style={{backgroundImage:`url(${x.image})`}}><span className="tag">{x.type}</span></div><div className="body"><h3>{x.title}</h3><div className="meta"><span>📍 {x.place}</span><span>{x.price}</span></div><p className="muted">{x.desc}</p><a className="btn ghost" href="/demande">Demander les détails →</a></div></article>}
function LeadForm(){const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,type:'TRAVEL_REQUEST'})});if(r.ok){setSent(true);form.reset()}else alert('Impossible d’envoyer la demande.')}catch{alert('Vérifiez votre connexion puis réessayez.')}finally{setBusy(false)}}if(sent)return <div className="form"><h2>Demande reçue ✓</h2><p className="muted">Merci. Votre demande est prête à être traitée par In Vacation Travel.</p><a className="btn primary" href="/">Retour à l’accueil</a></div>;return <form className="form" onSubmit={submit}><div className="head"><div><span className="eyebrow">Demande personnalisée</span><h2>Construisons votre voyage</h2><p>Donnez-nous les grandes lignes. Les tarifs et disponibilités seront confirmés par l’agence.</p></div></div><div className="fields"><div className="field"><label>Nom complet</label><input name="name" required placeholder="Votre nom"/></div><div className="field"><label>Téléphone</label><input name="phone" required placeholder="0550..."/></div><div className="field"><label>Email</label><input name="email" type="email" placeholder="vous@email.com"/></div><div className="field"><label>Destination</label><input name="destination" placeholder="Istanbul, Tunis, Dubai..."/></div><div className="field"><label>Date souhaitée</label><input name="date" type="date"/></div><div className="field"><label>Voyageurs</label><select name="travelers"><option>1–2</option><option>3–5</option><option>6+</option></select></div><div className="field full"><label>Votre projet</label><textarea name="message" placeholder="Budget indicatif, préférences, besoins visa/hôtel/vol..."/></div><div className="field full"><button className="btn primary" disabled={busy}>{busy?'Envoi…':'Envoyer ma demande'}</button></div></div></form>}

export default function Page({params}:{params:Promise<{slug?:string[]}>}){const [slug,setSlug]=useState<string>('');useMemo(()=>{params.then(p=>setSlug(p.slug?.join('/')||''))},[params]);const path=slug.toLowerCase();const isHome=path==='';const isForm=path==='demande';const filtered=trips.filter(x=>path==='voyages'||path==='offres'||x.type.toLowerCase().includes(path)||x.place.toLowerCase().includes(path));
if(isForm)return <><Header/><main className="section"><div className="container"><LeadForm/></div></main><Footer/></>;
if(isHome)return <><Header/><main><section className="hero"><div className="container"><span className="eyebrow">Votre prochaine escapade commence ici</span><h1>Voyagez mieux.<br/><span style={{color:'var(--cyan)'}}>Vivez plus.</span></h1><p>Une expérience digitale simple pour découvrir des destinations, comparer vos envies et demander un voyage personnalisé depuis Khemis Miliana.</p><Search/></div></section><section className="section"><div className="container"><div className="head"><div><span className="eyebrow">À découvrir</span><h2>Des idées pour partir</h2><p>Quelques inspirations. Chaque offre est à confirmer selon les dates, la disponibilité et votre demande.</p></div><a className="btn ghost" href="/voyages">Voir tous les voyages</a></div><div className="grid">{trips.slice(0,3).map(x=><Card key={x.title} x={x}/>)}</div></div></section><section className="section mist"><div className="container"><div className="head"><div><span className="eyebrow">Services</span><h2>Tout préparer au même endroit</h2></div></div><div className="grid">{services.map(s=><div className="card service" key={s[1]}><div className="icon">{s[0]}</div><h3>{s[1]}</h3><p className="muted">{s[2]}</p><a href="/demande">En savoir plus →</a></div>)}</div></div></section><section className="section"><div className="container"><div className="head"><div><span className="eyebrow">Destinations</span><h2>Où avez-vous envie d’aller ?</h2></div><a className="btn ghost" href="/destinations">Explorer</a></div><div className="grid">{destinations.map(d=><a className="card dest" href="/destinations" key={d[0]}><div className="photo" style={{backgroundImage:`url(${d[2]})`}}><div className="overlay"><h3>{d[0]}</h3><div>{d[1]}</div></div></div></a>)}</div></div></section><section className="section mist"><div className="container"><div className="cta"><div><span className="eyebrow">Projet de voyage</span><h2>Vous savez où partir ?</h2><p style={{color:'#c5d7dd'}}>Décrivez-nous votre projet et recevez une réponse personnalisée.</p></div><a className="btn primary" href="/demande">Préparer mon voyage →</a></div></div></section></main><Footer/></>;
return <><Header/><main className="section"><div className="container"><div className="head"><div><span className="eyebrow">In Vacation Travel</span><h2>{path==='destinations'?'Destinations':path==='billetterie'?'Billetterie':path==='hotellerie'?'Hôtellerie':path==='visa'?'Visa & accompagnement':path==='omra'?'Omra':path==='contact'?'Contact':path==='a-propos'?'À propos':'Voyages & offres'}</h2><p>Découvrez nos possibilités et faites-nous part de votre besoin. Les informations commerciales sont confirmées au cas par cas.</p></div><a className="btn primary" href="/demande">Demander un devis</a></div>{path==='contact'?<div className="grid"><div className="card service"><h3>Nous contacter</h3><p className="muted">44 Rue Colonel Bougara, Khemis Miliana 44000, Aïn Defla.</p><a className="btn primary" href="tel:+213552426512">Appeler le 0552 42 65 12</a></div><div className="card service"><h3>Préparer une demande</h3><p className="muted">Vol, hôtel, visa, Omra ou séjour : décrivez votre projet en ligne.</p><a className="btn dark" href="/demande">Ouvrir le formulaire</a></div></div>:<div className="grid">{filtered.length?filtered.map(x=><Card key={x.title} x={x}/>):trips.map(x=><Card key={x.title} x={x}/>)}</div>}</div></main><Footer/></>}
